import Head from "next/head";
import Layout from "../component/Layout";
import Header from "../component/Header";
import Footer from "../component/Footer";
import Hero from "../component/Hero";
import css from "../styles/Home.module.css";
import Services from "../component/Services";
export default function Home() {
  return (
        <Layout>
         <div className={css.container}>
        
        
        <Head>
          <title>FoodDilivery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
         <Hero/>   
         <Services/>   
        </main>
      
       
      </div>
        </Layout> 
     
      
     
  );

  
}
